### ISSUE TITLE
Tab mgmt APIs?

### ISSUE THREAD

**Issue by goodboy** [jpramosi/geckordp#11]
I know as per #9 and #10 that there are definitely tab *reading* methods but is there any way to create new tabs, and further possibly *unload* or *discard* those tabs during creation?

For example I'd like to be able to do something like what the []() does but dynamically 😎 

---
For some examples ideally we could use some of these subsys apis to accomplish this:
- the [tabs discard api](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/discard) that is normally only exposed to js addons
  - does the `Actor.eval()` method allow us to call APIs like this?
- `marionette` has an [`WindoManagerMixin.open_tab()`](https://github.com/mozilla/gecko-dev/blob/1105e2be1b4a23b160b2965114e78039ac5aa204/testing/marionette/harness/marionette_harness/runner/mixins/window_manager.py#L58) which seems [to call the "web driver API" underneath](https://github.com/mozilla/gecko-dev/blob/master/testing/marionette/client/marionette_driver/marionette.py#L1480) which in turn means calling a `self._send_message("WebDriver:NewWindow", body)` which is making an [underlying protocol request](https://github.com/mozilla/gecko-dev/blob/master/testing/marionette/client/marionette_driver/transport.py#L375) but i have no idea if this protocol or its APIs are accessible over RDP?

---
Probably more discussion / research results to come..

**Comment by jpramosi** [comment]
As far as I know the remote debug protocol is limited at this point (see https://github.com/mozilla/gecko-dev/tree/master/devtools/shared/specs). This limitation can also be seen if firefox connects via RDP with other firefox sessions. However it is possible to manage tabs with a webextension. But I think everything which uses the webextension api would require a separate project to handle all the heavy lifting.
But maybe something better can be utilized to do this.

**Comment by goodboy** [comment]
Cool, I'm asking in the webdriver room on matrix to see if anyone has thoughts on an alt approach to a webextension.

**Comment by goodboy** [comment]
@jpramosi could we maybe utilize the `WebConsole.evaluate_js_async()` stuff?

I'm not sure what access to internal APIs that might have but seems like [tabs APIs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs) would likely be in that set no?

**Comment by jpramosi** [comment]
Maybe it is possible to evaluate Javascript code in another context (actor or window ID) which is related to a webextension.
Atleast the [spec](https://github.com/mozilla/gecko-dev/blob/4a165cef2bdc2e79fddf256e5f5bd42e7c0ca058/devtools/shared/specs/webconsole.js#L149) would allow this.
