### ISSUE TITLE
Cookie Storage example always timesout

### ISSUE THREAD

**Issue by 266918** [jpramosi/geckordp#14]
Browser is up and showing the cookie set page but the cookie future is timing out even increase it to 10+ seconds
File "/Users/liutao/projects/maxmypoint/HotelChecker/ffcookie.py", line 96, in main
    cookie_resource = cookie_fut.result(13.0)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 460, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError

**Comment by jpramosi** [comment]
Thank you for your report. I just ran the tests and the storage related functions are broken on newer Firefox versions. I will tackle these issues if I got the time.

**Comment by jpramosi** [comment]
Okay, everything is working again. You can see the changes [here](https://github.com/jpramosi/geckordp/commit/fff82f4b8cf0804c3137446e5c08a17582eea7f0#diff-06c931dfa9c47d89c8020805546cbfcb85c2ecae9b0dac31f0cc05a2c1ff305b).
