### ISSUE TITLE
How to execute js code in Browser Console?

### ISSUE THREAD

**Issue by hkfsc** [jpramosi/geckordp#3]
I want to execute js code in Browser Console(Ctrl+Shift+J) rather than invoke it in single tab, is that possible?
And how can I call the extension API to execute something like `localStorage`?
Thanks

**Comment by hkfsc** [comment]
After reading your documents, I still dont know how to locate a element on the page and how to use those actors....

**Comment by jpramosi** [comment]
I believe executing javascript code in Developer's Browser Console is not feasible. Maybe you can ask the Firefox developers  on their [matrix](https://chat.mozilla.org)-[channels](https://wiki.mozilla.org/Matrix#Software_Development) whether it is possible with the remote debug protocol.
However you can execute the code in different frames (WindowGlobalActor.list_frames) or inner windows.

At the moment no API is available in Geckordp for accessing storage objects (cookies, localStorage, sessionStorage, extensionStorage, Cache).
However I will implement the [StorageActor](https://github.com/mozilla/gecko-dev/blob/master/devtools/shared/specs/storage.js) if I have time.

**Comment by jpramosi** [comment]
[Resolved](https://github.com/jpramosi/geckordp/blob/master/CHANGELOG.md#0430)
