### ISSUE TITLE
Can I have evaluate_js sync function rather than evaluate_js_async?

### ISSUE THREAD

**Issue by hkfsc** [jpramosi/geckordp#4]
I can do the sync work for using time.sleep and loop to get the results, but still, it will be more nice if you can provide this function built in, thanks!

**Comment by jpramosi** [comment]
It would be handy to have this function. I know some changes to Geckordp would be useful for typical common tasks.
However the core concept of Geckordp is to only provide a clean implementation of the remote debug protocol for Firefox.
Maybe a separate project would be ideal for such improvements.
Nonetheless I think I can add an example for how to create a 'evaluate_js_sync' function with future and wait, if I have time.
