### ISSUE TITLE
Can we have `to` field after calling the Web.navigate_to function?

### ISSUE THREAD

**Issue by hkfsc** [jpramosi/geckordp#5]
Can we have `to` field after calling the Web.navigate_to function? If not, I can only reget tab actor info from the client.

**Comment by jpramosi** [comment]
If I understand it correctly you would like to get the actual url after calling 'navigate_to'. 
The reasons why i won't implement such improvements are mentioned in your other [issue](https://github.com/jpramosi/geckordp/issues/4#issuecomment-1126985381).

**Comment by hkfsc** [comment]
> If I understand it correctly you would like to get the actual url after calling 'navigate_to'. The reasons why i won't implement such improvements are mentioned in your other [issue](https://github.com/jpramosi/geckordp/issues/4#issuecomment-1126985381).

I mean the actor, I can get the `from` actor after invoking the method, but the `from` actor is not reusable for executing the remain code, because it have been "moved" to another URL, thought the tab position haven't been changed(tab one is still the tab one, only different is that its URL have been changed), so if I still want to change something after `navigate_to`, I need to reget the tab's(tab one) actor, otherwise it will throw an exception, so if `navigate_to` can return the `to` field for getting the refreshed tab actor, I will not need to call other methods only for getting the new actor for the tab(one).

**Comment by jpramosi** [comment]
I see, that is typical for Firefox to detach actors after page visits. However to overcome this problem (and a few other like stucks in navigation, bad mutli-tab support, etc), i think a different project which builds upon Geckordp would be better for this sort of changes or improvements else this project loses its focus on the RDP API and become too bloated.

**Comment by hkfsc** [comment]
Sure, I agree with the idea of keeping this repo clean, hope I can provide some help and well to know!
