### ISSUE TITLE
How to disable error log form geckordp?

### ISSUE THREAD

**Issue by hkfsc** [jpramosi/geckordp#7]
Keep getting this error after restarted the firefox:
```
2022-06-03 11:09:24,550 [geckordp][ERROR] - wait_process_loaded(): waiting for process[5876] failed, wait 15 seconds:
process no longer exists (pid=5876)
```

**Comment by jpramosi** [comment]
At the moment there is no variable to set the log level (I will add this later).
Though you can set the log level to fatal, if you really would like to disable all errors:
```
from geckordp.logger import set_stdout_log_level, logging
set_stdout_log_level(logging.FATAL)
```
But how is the error reproduced exactly? It looks like the process is already terminated before it can wait for it.
