### ISSUE TITLE
How to click and input text?

### ISSUE THREAD

**Issue by hkfsc** [jpramosi/geckordp#8]

**Comment by jpramosi** [comment]
Firefox its RDP implementation doesn't have any actors to directly interact with the html content like peripherals would do. Though it's possible to use javascript with [evaluate_js_async()](https://github.com/jpramosi/geckordp/blob/86fada5edd0216b78d2dbc9d92d87a8e024cd829/geckordp/actors/web_console.py#L59):
```javascript
let textbox = document.querySelector("#suggestion-search");
textbox.focus();
textbox.select();
textbox.value = "test";
```
However it might not work for every website.
